name: CI

on:
    push:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: action/setup-node@v3
              with:
                node-version: 18
            - run: npm install

            - name: Linter
              run: npx eslint src/
              continue-on-error: true

            - name: Linter results
              run: |
                if npx eslint src/; then
                  echo "::notice:: Linter OK"
                else
                  echo "::error:: Linter KO"
                fi

            - name: Tests
              run: npm test
              continue-on-error: true

            - name: Tests results
              run: |
                if npm test; then
                  echo "::notice:: tests OK"
                else
                  echo "::error:: Tests KO"
                fi

            - run: npm audit 